# this needed to check success
management:
  endpoints:
    web:
      exposure:
        include: health, info
# Datadog tracing configuration
dd:
  trace:
    enabled: true
  service:
    name: my-service
  env: development
  version: 1.0.0
